# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee5f6f23c4d9f5952c57a8d17385904d63d430c67825d53b676b58bf470b4b20d6676c2923d4a1609a73ccfb3ed8055b61b6b94090a59d83bb825912068287ec

test:
  secret_key_base: a227c14baaed7d030448060092c666cc51a745120fdd42f230d5c3a4727d0eee915ba3b8ec3a2776b9c50299543e10d372b1bf756a7f156df8361e16f00f1d9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
